// Copyright 2026 VirtusCo
// Generates ROS 2 Python launch files from node configurations

import { LaunchNodeConfig } from '../types';

// ── Launch Templates ────────────────────────────────────────────────

export interface LaunchTemplate {
  pkg: string;
  executable: string;
  defaultName: string;
  defaultParams: Record<string, string | number | boolean>;
  defaultRemappings: Record<string, string>;
}

export const LAUNCH_TEMPLATES: LaunchTemplate[] = [
  {
    pkg: 'ydlidar_driver',
    executable: 'ydlidar_driver_node',
    defaultName: 'ydlidar_driver',
    defaultParams: {
      port: '/dev/ydlidar',
      baudrate: 128000,
      frame_id: 'laser_frame',
      single_channel: true,
      frequency: 7.0,
    },
    defaultRemappings: {},
  },
  {
    pkg: 'porter_lidar_processor',
    executable: 'lidar_processor_node',
    defaultName: 'porter_lidar_processor',
    defaultParams: {
      min_range: 0.12,
      max_range: 12.0,
      noise_threshold: 0.05,
    },
    defaultRemappings: {
      '/scan_in': '/scan',
      '/scan_out': '/scan/processed',
    },
  },
  {
    pkg: 'porter_orchestrator',
    executable: 'orchestrator_node',
    defaultName: 'porter_orchestrator',
    defaultParams: {
      health_check_interval: 2.0,
      passenger_timeout: 30.0,
    },
    defaultRemappings: {},
  },
  {
    pkg: 'porter_esp32_bridge',
    executable: 'motor_bridge_node',
    defaultName: 'esp32_motor_bridge',
    defaultParams: {
      serial_port: '/dev/ttyUSB0',
      baud_rate: 115200,
      watchdog_timeout: 500,
    },
    defaultRemappings: {},
  },
  {
    pkg: 'porter_ai_assistant',
    executable: 'ai_assistant_node',
    defaultName: 'porter_ai_assistant',
    defaultParams: {
      model_path: '/opt/porter/models/qwen2.5-1.5b-instruct-q4_k_m.gguf',
      n_threads: 2,
      n_ctx: 1024,
    },
    defaultRemappings: {},
  },
];

// ── Launch File Generator ───────────────────────────────────────────

/**
 * Generates a ROS 2 Python launch file from node configurations.
 */
export class LaunchGenerator {
  /**
   * Generates a valid ROS 2 Python launch file string.
   */
  generateLaunchPy(nodes: LaunchNodeConfig[]): string {
    const lines: string[] = [];

    // Header
    lines.push('# Copyright 2026 VirtusCo');
    lines.push('# Auto-generated by Virtus ROS 2 Studio');
    lines.push('');
    lines.push('from launch import LaunchDescription');
    lines.push('from launch_ros.actions import Node');
    lines.push('');
    lines.push('');
    lines.push('def generate_launch_description():');
    lines.push('    return LaunchDescription([');

    // Node entries
    for (let i = 0; i < nodes.length; i++) {
      const node = nodes[i];
      const isLast = i === nodes.length - 1;

      lines.push('        Node(');
      lines.push(`            package='${node.pkg}',`);
      lines.push(`            executable='${node.executable}',`);
      lines.push(`            name='${node.name}',`);

      // Parameters
      if (Object.keys(node.params).length > 0) {
        lines.push('            parameters=[{');
        const paramEntries = Object.entries(node.params);
        for (let j = 0; j < paramEntries.length; j++) {
          const [key, value] = paramEntries[j];
          const comma = j < paramEntries.length - 1 ? ',' : '';
          if (typeof value === 'string') {
            lines.push(`                '${key}': '${value}'${comma}`);
          } else if (typeof value === 'boolean') {
            lines.push(`                '${key}': ${value ? 'True' : 'False'}${comma}`);
          } else {
            lines.push(`                '${key}': ${value}${comma}`);
          }
        }
        lines.push('            }],');
      }

      // Remappings
      if (Object.keys(node.remappings).length > 0) {
        lines.push('            remappings=[');
        const remapEntries = Object.entries(node.remappings);
        for (let j = 0; j < remapEntries.length; j++) {
          const [from, to] = remapEntries[j];
          const comma = j < remapEntries.length - 1 ? ',' : '';
          lines.push(`                ('${from}', '${to}')${comma}`);
        }
        lines.push('            ],');
      }

      lines.push(`        )${isLast ? '' : ','}`);
    }

    lines.push('    ])');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Returns the list of available launch templates.
   */
  getTemplates(): LaunchTemplate[] {
    return [...LAUNCH_TEMPLATES];
  }

  /**
   * Creates a LaunchNodeConfig from a template.
   */
  fromTemplate(template: LaunchTemplate): LaunchNodeConfig {
    return {
      pkg: template.pkg,
      executable: template.executable,
      name: template.defaultName,
      params: { ...template.defaultParams },
      remappings: { ...template.defaultRemappings },
    };
  }

  /**
   * Generates a launch.py from canvas node state (used by the Launch Builder).
   * Each canvas node becomes a Node() in the launch description with all
   * configured parameters and remappings derived from edge connections.
   */
  generateFromCanvas(
    canvasNodes: {
      name: string;
      pkg: string;
      executable: string;
      params: Record<string, string | number | boolean>;
      inputs: { id: string; topic: string; msgType: string }[];
      outputs: { id: string; topic: string; msgType: string }[];
    }[]
  ): string {
    const lines: string[] = [];

    lines.push('# Copyright 2026 VirtusCo');
    lines.push('# Auto-generated by Virtus ROS 2 Studio — Launch Builder Canvas');
    lines.push('');
    lines.push('import os');
    lines.push('');
    lines.push('from launch import LaunchDescription');
    lines.push('from launch.actions import DeclareLaunchArgument');
    lines.push('from launch.substitutions import LaunchConfiguration');
    lines.push('from launch_ros.actions import Node');
    lines.push('');
    lines.push('');
    lines.push('def generate_launch_description():');
    lines.push('    return LaunchDescription([');

    // use_sim_time argument
    lines.push("        DeclareLaunchArgument('use_sim_time', default_value='false',");
    lines.push("            description='Use simulation time'),");
    lines.push('');

    for (let i = 0; i < canvasNodes.length; i++) {
      const node = canvasNodes[i];
      const isLast = i === canvasNodes.length - 1;
      const nodeName = node.name.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '').toLowerCase();

      lines.push('        Node(');
      lines.push(`            package='${node.pkg}',`);
      lines.push(`            executable='${node.executable}',`);
      lines.push(`            name='${nodeName}',`);
      lines.push("            output='screen',");

      // Parameters
      if (Object.keys(node.params).length > 0) {
        lines.push('            parameters=[{');
        const paramEntries = Object.entries(node.params);
        for (let j = 0; j < paramEntries.length; j++) {
          const [key, value] = paramEntries[j];
          const comma = j < paramEntries.length - 1 ? ',' : '';
          if (typeof value === 'string') {
            lines.push(`                '${key}': '${value}'${comma}`);
          } else if (typeof value === 'boolean') {
            lines.push(`                '${key}': ${value ? 'True' : 'False'}${comma}`);
          } else {
            lines.push(`                '${key}': ${value}${comma}`);
          }
        }
        lines.push("            }, {'use_sim_time': LaunchConfiguration('use_sim_time')}],");
      } else {
        lines.push("            parameters=[{'use_sim_time': LaunchConfiguration('use_sim_time')}],");
      }

      lines.push(`        )${isLast ? '' : ','}`);
    }

    lines.push('    ])');
    lines.push('');

    return lines.join('\n');
  }
}
