// Copyright 2026 VirtusCo
// C source and header file generators

export function renderHeader(
  headerLines: string[],
  includes: Set<string>
): string {
  const lines: string[] = [
    '/* Auto-generated by Virtus Firmware Builder — DO NOT EDIT */',
    '/* Re-generate from the .virtusflow canvas */',
    '',
    '#ifndef VIRTUS_GENERATED_H',
    '#define VIRTUS_GENERATED_H',
    '',
    '#include <zephyr/kernel.h>',
  ];

  // Add detected includes (deduplicated, sorted)
  const sortedIncludes = [...includes].sort();
  for (const inc of sortedIncludes) {
    if (inc !== '#include <zephyr/kernel.h>') {
      lines.push(inc);
    }
  }

  lines.push('');

  // Add node-specific declarations
  for (const code of headerLines) {
    lines.push(code);
    lines.push('');
  }

  lines.push('/** Initialize all configured peripherals and RTOS objects. */');
  lines.push('void virtus_init(void);');
  lines.push('');
  lines.push('#endif /* VIRTUS_GENERATED_H */');
  lines.push('');

  return lines.join('\n');
}

export function renderSource(
  initLines: string[],
  loopLines: string[]
): string {
  const lines: string[] = [
    '/* Auto-generated by Virtus Firmware Builder — DO NOT EDIT */',
    '/* Re-generate from the .virtusflow canvas */',
    '',
    '#include "virtus_generated.h"',
    '',
  ];

  // Add individual init/helper functions embedded in initLines
  // (they may contain full function bodies, not just single lines)
  const functionBodies: string[] = [];
  const bareInitCalls: string[] = [];

  for (const code of initLines) {
    if (code.includes('void ') || code.includes('int ') || code.includes('static ')) {
      // This is a function definition — place it before virtus_init
      functionBodies.push(code);
    } else {
      bareInitCalls.push(code);
    }
  }

  for (const body of functionBodies) {
    lines.push(body);
    lines.push('');
  }

  lines.push('void virtus_init(void) {');

  if (bareInitCalls.length === 0 && functionBodies.length === 0) {
    lines.push('    /* No peripherals configured yet */');
  }

  for (const call of bareInitCalls) {
    for (const line of call.split('\n')) {
      lines.push('    ' + line);
    }
  }

  lines.push('}');
  lines.push('');

  // Optional loop body (if any nodes define loop code)
  if (loopLines.length > 0) {
    lines.push('void virtus_loop(void) {');
    for (const code of loopLines) {
      for (const line of code.split('\n')) {
        lines.push('    ' + line);
      }
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}
