// Copyright 2026 VirtusCo
// Kconfig prj.conf generator

export type OptimizationProfile = 'debug' | 'release_size' | 'release_speed' | 'none';

const OPTIMIZATION_FLAGS: Record<OptimizationProfile, string[]> = {
  debug: [
    '# Optimization: Debug (-Og, full debug info)',
    'CONFIG_DEBUG_OPTIMIZATIONS=y',
    'CONFIG_DEBUG_INFO=y',
    'CONFIG_DEBUG_THREAD_INFO=y',
    'CONFIG_ASSERT=y',
    'CONFIG_LOG=y',
    'CONFIG_LOG_DEFAULT_LEVEL=4',
    'CONFIG_PRINTK=y',
  ],
  release_size: [
    '# Optimization: Release Size (-Os, stripped)',
    'CONFIG_SIZE_OPTIMIZATIONS=y',
    'CONFIG_DEBUG_INFO=n',
    'CONFIG_ASSERT=n',
    'CONFIG_LOG_DEFAULT_LEVEL=1',
    'CONFIG_PRINTK=y',
    'CONFIG_LTO=y',
    'CONFIG_COMPILER_OPT="-ffunction-sections -fdata-sections"',
    'CONFIG_LINKER_ORPHAN_SECTION_PLACE=y',
  ],
  release_speed: [
    '# Optimization: Release Speed (-O2)',
    'CONFIG_SPEED_OPTIMIZATIONS=y',
    'CONFIG_DEBUG_INFO=n',
    'CONFIG_ASSERT=n',
    'CONFIG_LOG_DEFAULT_LEVEL=1',
    'CONFIG_PRINTK=y',
    'CONFIG_LTO=y',
  ],
  none: [
    '# Optimization: None (-O0, for debugging)',
    'CONFIG_NO_OPTIMIZATIONS=y',
    'CONFIG_DEBUG_INFO=y',
    'CONFIG_ASSERT=y',
    'CONFIG_LOG=y',
    'CONFIG_LOG_DEFAULT_LEVEL=4',
  ],
};

export function renderConfFlags(
  flags: Set<string>,
  optimization: OptimizationProfile = 'debug'
): string {
  const lines: string[] = [
    '# Auto-generated by Virtus Firmware Builder — DO NOT EDIT',
    '# Re-generate from the .virtusflow canvas',
    '',
  ];

  // Add optimization profile first
  for (const optLine of OPTIMIZATION_FLAGS[optimization]) {
    lines.push(optLine);
  }
  lines.push('');

  // Group and sort remaining flags for readability
  const sorted = [...flags].sort();
  const groups: Record<string, string[]> = {};

  for (const flag of sorted) {
    // Skip optimization flags already added above
    if (flag.includes('OPTIMIZATION') || flag.includes('DEBUG_INFO') ||
        flag.includes('LTO') || flag.includes('ASSERT') ||
        flag.includes('NO_OPTIMIZATIONS')) continue;

    const match = flag.match(/^CONFIG_(\w+?)(?:_|=)/);
    const group = match ? match[1] : 'MISC';
    if (!groups[group]) groups[group] = [];
    groups[group].push(flag);
  }

  for (const [group, groupFlags] of Object.entries(groups)) {
    lines.push(`# ${group}`);
    for (const flag of groupFlags) {
      lines.push(flag);
    }
    lines.push('');
  }

  return lines.join('\n');
}
