// Copyright 2026 VirtusCo
// Device tree overlay generator

export function renderDTS(
  aliasFragments: string[],
  peripheralBlocks: string[]
): string {
  const lines: string[] = [
    '/* Auto-generated by Virtus Firmware Builder — DO NOT EDIT */',
    '/* Re-generate from the .virtusflow canvas */',
    '',
  ];

  // Alias block
  if (aliasFragments.length > 0) {
    lines.push('/ {');
    lines.push('    aliases {');
    for (const fragment of aliasFragments) {
      for (const line of fragment.split('\n')) {
        const trimmed = line.trim();
        if (trimmed) lines.push('        ' + trimmed);
      }
    }
    lines.push('    };');
    lines.push('};');
    lines.push('');
  }

  // Peripheral node blocks (e.g., &ledc0, &uart0, etc.)
  for (const block of peripheralBlocks) {
    lines.push(block);
    lines.push('');
  }

  return lines.join('\n') + '\n';
}
