// Copyright 2026 VirtusCo

import { PCBDesign } from './PCBTypes';
import { FOOTPRINT_LIBRARY } from './FootprintLibrary';

export class NetlistExporter {
  exportKicadNetlist(design: PCBDesign): string {
    const lines: string[] = [];

    lines.push('(export (version "E")');
    lines.push('  (design');
    lines.push(`    (source "${design.name}")`);
    lines.push('    (tool "Virtus PCB Studio 1.0")');
    lines.push('  )');

    // Components
    lines.push('  (components');
    for (const fp of design.footprints) {
      const fpDef = FOOTPRINT_LIBRARY.find((f) => f.id === fp.footprintId);
      lines.push(`    (comp (ref "${fp.reference}")`);
      lines.push(`      (value "${fp.value}")`);
      lines.push(`      (footprint "${fpDef?.name || fp.footprintId}")`);
      lines.push('    )');
    }
    lines.push('  )');

    // Nets
    const allNets = new Set<string>();
    for (const fp of design.footprints) {
      for (const pad of fp.pads) {
        if (pad.net) { allNets.add(pad.net); }
      }
    }

    lines.push('  (nets');
    lines.push('    (net (code "0") (name ""))');
    let netCode = 1;
    for (const net of allNets) {
      lines.push(`    (net (code "${netCode}") (name "${net}")`);

      // Find all pads on this net
      for (const fp of design.footprints) {
        for (const pad of fp.pads) {
          if (pad.net === net) {
            lines.push(`      (node (ref "${fp.reference}") (pin "${pad.padId}"))`);
          }
        }
      }

      lines.push('    )');
      netCode++;
    }
    lines.push('  )');

    lines.push(')');
    return lines.join('\n');
  }

  exportIPC356(design: PCBDesign): string {
    const lines: string[] = [];

    // Header
    lines.push('C  IPC-D-356 Netlist');
    lines.push('C  Generated by Virtus PCB Studio');
    lines.push(`C  Design: ${design.name}`);
    lines.push('P  VER IPC-D-356');
    lines.push('P  UNITS CUST 0');

    // Net records
    // IPC-356 format: 317 netname   refdes-pin  Xcoord Ycoord
    for (const fp of design.footprints) {
      for (const pad of fp.pads) {
        const netName = pad.net || 'N/C';
        const refPin = `${fp.reference}-${pad.padId}`;

        // Coordinates in 0.0001 inch (mils * 10)
        const xMils = Math.round(pad.position.x * 39.3701 * 10);
        const yMils = Math.round(pad.position.y * 39.3701 * 10);

        // Format: 317 followed by net name (14 chars), component-pin, coordinates
        const netField = netName.padEnd(14);
        const refField = refPin.padEnd(14);
        const xField = (xMils >= 0 ? '+' : '') + xMils.toString().padStart(6, '0');
        const yField = (yMils >= 0 ? '+' : '') + yMils.toString().padStart(6, '0');

        lines.push(`317${netField}${refField}  X${xField}Y${yField}`);
      }
    }

    // Test access records for through-hole pads
    for (const fp of design.footprints) {
      const fpDef = FOOTPRINT_LIBRARY.find((f) => f.id === fp.footprintId);
      if (!fpDef) { continue; }

      for (let i = 0; i < fpDef.pads.length; i++) {
        if (fpDef.pads[i].type !== 'thru_hole') { continue; }

        const pad = fp.pads[i];
        if (!pad) { continue; }

        const xMils = Math.round(pad.position.x * 39.3701 * 10);
        const yMils = Math.round(pad.position.y * 39.3701 * 10);
        const drill = fpDef.pads[i].drill || 0;
        const drillMils = Math.round(drill * 39.3701);

        const xField = (xMils >= 0 ? '+' : '') + xMils.toString().padStart(6, '0');
        const yField = (yMils >= 0 ? '+' : '') + yMils.toString().padStart(6, '0');

        lines.push(`327${fp.reference.padEnd(14)}${pad.padId.padEnd(14)}  X${xField}Y${yField}D${drillMils.toString().padStart(4, '0')}A00`);
      }
    }

    lines.push('999');
    return lines.join('\n');
  }
}
