// Copyright 2026 VirtusCo
// Production-grade ROS 2 package code generator from Launch Builder canvas

// ── Interfaces ──────────────────────────────────────────────────────

export interface CanvasNodeConfig {
  name: string;
  publishers: { topic: string; msgType: string; hz: number }[];
  subscribers: { topic: string; msgType: string; callback: string }[];
  services: { name: string; srvType: string; role: 'server' | 'client' }[];
  actions: { name: string; actionType: string; role: 'server' | 'client' }[];
  timers: { periodMs: number; callback: string }[];
  parameters: { name: string; type: 'string' | 'int' | 'float' | 'bool'; default: string }[];
  lifecycle: boolean;
}

export interface PackageGenConfig {
  name: string;
  description: string;
  language: 'cpp' | 'python';
  nodes: CanvasNodeConfig[];
  dependencies: string[];
}

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface GeneratedPackage {
  files: GeneratedFile[];
}

// ── Code Generator ──────────────────────────────────────────────────

export class ROS2CodeGenerator {
  /**
   * Generates a complete ROS 2 package from canvas configuration.
   */
  generatePackage(config: PackageGenConfig): GeneratedPackage {
    const allDeps = this.computeDependencies(config);
    const files: GeneratedFile[] = [];

    if (config.language === 'python') {
      files.push(...this.generatePythonPackage(config, allDeps));
    } else {
      files.push(...this.generateCppPackage(config, allDeps));
    }

    // Generate launch file (shared between Python and C++)
    files.push(this.generateLaunchFile(config));

    // Generate params YAML
    files.push(this.generateParamsYaml(config));

    return { files };
  }

  // ── Dependency Computation ────────────────────────────────────────

  private computeDependencies(config: PackageGenConfig): string[] {
    const deps = new Set<string>(config.dependencies);

    // Always required
    if (config.language === 'cpp') {
      deps.add('rclcpp');
    } else {
      deps.add('rclpy');
    }

    // Add lifecycle dependencies
    for (const node of config.nodes) {
      if (node.lifecycle) {
        if (config.language === 'cpp') {
          deps.add('rclcpp_lifecycle');
          deps.add('lifecycle_msgs');
        } else {
          deps.add('rclpy');
          deps.add('lifecycle_msgs');
        }
      }

      // Add message package deps from publishers/subscribers
      for (const pub of node.publishers) {
        const pkg = msgTypeToPackage(pub.msgType);
        if (pkg) deps.add(pkg);
      }
      for (const sub of node.subscribers) {
        const pkg = msgTypeToPackage(sub.msgType);
        if (pkg) deps.add(pkg);
      }
      for (const srv of node.services) {
        const pkg = msgTypeToPackage(srv.srvType);
        if (pkg) deps.add(pkg);
      }
      for (const action of node.actions) {
        const pkg = msgTypeToPackage(action.actionType);
        if (pkg) deps.add(pkg);
        deps.add('rclpy' === config.language ? 'rclpy' : 'rclcpp_action');
      }
    }

    return Array.from(deps).sort();
  }

  // ── Python Package Generation ─────────────────────────────────────

  private generatePythonPackage(config: PackageGenConfig, deps: string[]): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const pkgName = config.name;

    // package.xml
    files.push({
      path: 'package.xml',
      content: this.generatePackageXml(config, deps, 'ament_python'),
    });

    // setup.py
    const entryPoints = config.nodes
      .map((n) => `            '${toSnakeCase(n.name)} = ${pkgName}.${toSnakeCase(n.name)}:main',`)
      .join('\n');

    files.push({
      path: 'setup.py',
      content: `# Copyright 2026 VirtusCo
# Auto-generated by Virtus ROS 2 Studio

from setuptools import find_packages, setup

package_name = '${pkgName}'

setup(
    name=package_name,
    version='0.1.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages', ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name + '/launch', ['launch/${pkgName}_launch.py']),
        ('share/' + package_name + '/config', ['config/${pkgName}_params.yaml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='VirtusCo',
    maintainer_email='dev@virtusco.io',
    description='${config.description}',
    license='Proprietary',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
${entryPoints}
        ],
    },
)
`,
    });

    // setup.cfg
    files.push({
      path: 'setup.cfg',
      content: `[develop]
script_dir=$base/lib/${pkgName}

[install]
install_scripts=$base/lib/${pkgName}
`,
    });

    // resource/<pkg_name> — ament index marker
    files.push({
      path: `resource/${pkgName}`,
      content: '',
    });

    // __init__.py
    files.push({
      path: `${pkgName}/__init__.py`,
      content: `# Copyright 2026 VirtusCo
`,
    });

    // Generate each node file
    for (const node of config.nodes) {
      files.push({
        path: `${pkgName}/${toSnakeCase(node.name)}.py`,
        content: this.generatePythonNode(node, pkgName),
      });
    }

    return files;
  }

  private generatePythonNode(node: CanvasNodeConfig, pkgName: string): string {
    const className = toPascalCase(node.name);
    const lines: string[] = [];

    // Header
    lines.push('# Copyright 2026 VirtusCo');
    lines.push(`# Auto-generated by Virtus ROS 2 Studio — ${className} node`);
    lines.push('');

    // Imports
    lines.push('import rclpy');
    if (node.lifecycle) {
      lines.push('from rclpy.lifecycle import LifecycleNode, LifecycleState, TransitionCallbackReturn');
    } else {
      lines.push('from rclpy.node import Node');
    }
    lines.push('from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy');

    // Collect unique message imports
    const msgImports = new Map<string, Set<string>>();
    for (const pub of node.publishers) {
      this.addPythonImport(msgImports, pub.msgType);
    }
    for (const sub of node.subscribers) {
      this.addPythonImport(msgImports, sub.msgType);
    }
    for (const srv of node.services) {
      this.addPythonImport(msgImports, srv.srvType, 'srv');
    }
    for (const action of node.actions) {
      this.addPythonImport(msgImports, action.actionType, 'action');
    }
    if (node.actions.length > 0) {
      lines.push('from rclpy.action import ActionServer, ActionClient');
    }

    for (const [importPath, names] of msgImports) {
      lines.push(`from ${importPath} import ${Array.from(names).join(', ')}`);
    }

    lines.push('');
    lines.push('');

    // QoS constants
    if (this.needsSensorQoS(node)) {
      lines.push('SENSOR_QOS = QoSProfile(');
      lines.push('    reliability=ReliabilityPolicy.RELIABLE,');
      lines.push('    history=HistoryPolicy.KEEP_LAST,');
      lines.push('    depth=5,');
      lines.push(')');
      lines.push('');
      lines.push('');
    }

    // Class definition
    const baseClass = node.lifecycle ? 'LifecycleNode' : 'Node';
    lines.push(`class ${className}(${baseClass}):`);
    lines.push(`    """${className} ROS 2 node for ${pkgName}."""`);
    lines.push('');

    // Constructor
    lines.push(`    def __init__(self):`);
    lines.push(`        super().__init__('${toSnakeCase(node.name)}')`);
    lines.push(`        self.get_logger().info('${className} initializing...')`);
    lines.push('');

    // Parameters
    if (node.parameters.length > 0) {
      lines.push('        # Parameters');
      for (const param of node.parameters) {
        const defaultVal = this.pythonDefaultValue(param.type, param.default);
        lines.push(`        self.declare_parameter('${param.name}', ${defaultVal})`);
      }
      lines.push('');
      for (const param of node.parameters) {
        lines.push(`        self._${param.name} = self.get_parameter('${param.name}').value`);
      }
      lines.push('');
    }

    // Publishers
    if (node.publishers.length > 0) {
      lines.push('        # Publishers');
      for (const pub of node.publishers) {
        const msgClass = msgTypeToClassName(pub.msgType);
        const varName = this.topicToVarName(pub.topic, 'pub');
        const qos = this.inferPythonQoS(pub.topic, pub.msgType);
        lines.push(`        self.${varName} = self.create_publisher(${msgClass}, '${pub.topic}', ${qos})`);
      }
      lines.push('');
    }

    // Subscribers
    if (node.subscribers.length > 0) {
      lines.push('        # Subscribers');
      for (const sub of node.subscribers) {
        const msgClass = msgTypeToClassName(sub.msgType);
        const varName = this.topicToVarName(sub.topic, 'sub');
        const callbackName = sub.callback || `${this.topicToCallbackName(sub.topic)}_callback`;
        const qos = this.inferPythonQoS(sub.topic, sub.msgType);
        lines.push(`        self.${varName} = self.create_subscription(${msgClass}, '${sub.topic}', self.${callbackName}, ${qos})`);
      }
      lines.push('');
    }

    // Service servers/clients
    if (node.services.length > 0) {
      lines.push('        # Services');
      for (const srv of node.services) {
        const srvClass = msgTypeToClassName(srv.srvType);
        const varName = this.topicToVarName(srv.name, srv.role === 'server' ? 'srv' : 'cli');
        if (srv.role === 'server') {
          lines.push(`        self.${varName} = self.create_service(${srvClass}, '${srv.name}', self.${this.topicToCallbackName(srv.name)}_callback)`);
        } else {
          lines.push(`        self.${varName} = self.create_client(${srvClass}, '${srv.name}')`);
        }
      }
      lines.push('');
    }

    // Action servers/clients
    if (node.actions.length > 0) {
      lines.push('        # Actions');
      for (const action of node.actions) {
        const actionClass = msgTypeToClassName(action.actionType);
        const varName = this.topicToVarName(action.name, action.role === 'server' ? 'action_srv' : 'action_cli');
        if (action.role === 'server') {
          lines.push(`        self.${varName} = ActionServer(self, ${actionClass}, '${action.name}', self.${this.topicToCallbackName(action.name)}_execute)`);
        } else {
          lines.push(`        self.${varName} = ActionClient(self, ${actionClass}, '${action.name}')`);
        }
      }
      lines.push('');
    }

    // Timers
    if (node.timers.length > 0) {
      lines.push('        # Timers');
      for (let i = 0; i < node.timers.length; i++) {
        const timer = node.timers[i];
        const callbackName = timer.callback || `timer_${i}_callback`;
        const period = timer.periodMs / 1000;
        lines.push(`        self._timer_${i} = self.create_timer(${period}, self.${callbackName})`);
      }
      lines.push('');
    }

    // Publisher timer callbacks (for periodic publishing)
    for (const pub of node.publishers) {
      if (pub.hz > 0) {
        const msgClass = msgTypeToClassName(pub.msgType);
        const varName = this.topicToVarName(pub.topic, 'pub');
        const callbackName = `${this.topicToCallbackName(pub.topic)}_publish`;
        const period = 1.0 / pub.hz;
        lines.push(`        self._${this.topicToCallbackName(pub.topic)}_timer = self.create_timer(${period.toFixed(4)}, self.${callbackName})`);
      }
    }
    if (node.publishers.some((p) => p.hz > 0)) {
      lines.push('');
    }

    lines.push(`        self.get_logger().info('${className} initialized')`);
    lines.push('');

    // Subscriber callbacks
    for (const sub of node.subscribers) {
      const msgClass = msgTypeToClassName(sub.msgType);
      const callbackName = sub.callback || `${this.topicToCallbackName(sub.topic)}_callback`;
      lines.push(`    def ${callbackName}(self, msg: ${msgClass}):`);
      lines.push(`        """Callback for ${sub.topic} subscriber."""`);
      lines.push(`        self.get_logger().debug(f'Received on ${sub.topic}: {msg}')`);
      lines.push('');
    }

    // Publisher timer callbacks
    for (const pub of node.publishers) {
      if (pub.hz > 0) {
        const msgClass = msgTypeToClassName(pub.msgType);
        const varName = this.topicToVarName(pub.topic, 'pub');
        const callbackName = `${this.topicToCallbackName(pub.topic)}_publish`;
        lines.push(`    def ${callbackName}(self):`);
        lines.push(`        """Periodic publish callback for ${pub.topic} at ${pub.hz} Hz."""`);
        lines.push(`        msg = ${msgClass}()`);
        lines.push(`        self.${varName}.publish(msg)`);
        lines.push(`        self.get_logger().debug(f'Published on ${pub.topic}')`);
        lines.push('');
      }
    }

    // Service callbacks
    for (const srv of node.services) {
      if (srv.role === 'server') {
        const srvClass = msgTypeToClassName(srv.srvType);
        const callbackName = `${this.topicToCallbackName(srv.name)}_callback`;
        lines.push(`    def ${callbackName}(self, request, response):`);
        lines.push(`        """Service handler for ${srv.name}."""`);
        lines.push(`        self.get_logger().info(f'Service ${srv.name} called')`);
        lines.push('        return response');
        lines.push('');
      }
    }

    // Action callbacks
    for (const action of node.actions) {
      if (action.role === 'server') {
        const callbackName = `${this.topicToCallbackName(action.name)}_execute`;
        lines.push(`    def ${callbackName}(self, goal_handle):`);
        lines.push(`        """Action execute callback for ${action.name}."""`);
        lines.push(`        self.get_logger().info(f'Executing action ${action.name}')`);
        lines.push('        goal_handle.succeed()');
        lines.push('        return goal_handle.request');
        lines.push('');
      }
    }

    // Timer callbacks
    for (let i = 0; i < node.timers.length; i++) {
      const timer = node.timers[i];
      const callbackName = timer.callback || `timer_${i}_callback`;
      lines.push(`    def ${callbackName}(self):`);
      lines.push(`        """Timer callback (period: ${timer.periodMs} ms)."""`);
      lines.push(`        self.get_logger().debug('Timer ${i} fired')`);
      lines.push('');
    }

    // Lifecycle callbacks
    if (node.lifecycle) {
      lines.push('    def on_configure(self, state: LifecycleState) -> TransitionCallbackReturn:');
      lines.push(`        """Handle configure transition."""`);
      lines.push(`        self.get_logger().info('Configuring...')`);
      lines.push('        return TransitionCallbackReturn.SUCCESS');
      lines.push('');
      lines.push('    def on_activate(self, state: LifecycleState) -> TransitionCallbackReturn:');
      lines.push(`        """Handle activate transition."""`);
      lines.push(`        self.get_logger().info('Activating...')`);
      lines.push('        return TransitionCallbackReturn.SUCCESS');
      lines.push('');
      lines.push('    def on_deactivate(self, state: LifecycleState) -> TransitionCallbackReturn:');
      lines.push(`        """Handle deactivate transition."""`);
      lines.push(`        self.get_logger().info('Deactivating...')`);
      lines.push('        return TransitionCallbackReturn.SUCCESS');
      lines.push('');
      lines.push('    def on_cleanup(self, state: LifecycleState) -> TransitionCallbackReturn:');
      lines.push(`        """Handle cleanup transition."""`);
      lines.push(`        self.get_logger().info('Cleaning up...')`);
      lines.push('        return TransitionCallbackReturn.SUCCESS');
      lines.push('');
      lines.push('    def on_shutdown(self, state: LifecycleState) -> TransitionCallbackReturn:');
      lines.push(`        """Handle shutdown transition."""`);
      lines.push(`        self.get_logger().info('Shutting down...')`);
      lines.push('        return TransitionCallbackReturn.SUCCESS');
      lines.push('');
    }

    // main()
    lines.push('');
    lines.push('def main(args=None):');
    lines.push(`    """Entry point for ${className}."""`);
    lines.push('    rclpy.init(args=args)');
    lines.push(`    node = ${className}()`);
    lines.push('    try:');
    lines.push('        rclpy.spin(node)');
    lines.push('    except KeyboardInterrupt:');
    lines.push(`        node.get_logger().info('${className} shutting down')`);
    lines.push('    finally:');
    lines.push('        node.destroy_node()');
    lines.push('        rclpy.shutdown()');
    lines.push('');
    lines.push('');
    lines.push("if __name__ == '__main__':");
    lines.push('    main()');
    lines.push('');

    return lines.join('\n');
  }

  // ── C++ Package Generation ────────────────────────────────────────

  private generateCppPackage(config: PackageGenConfig, deps: string[]): GeneratedFile[] {
    const files: GeneratedFile[] = [];
    const pkgName = config.name;

    // package.xml
    files.push({
      path: 'package.xml',
      content: this.generatePackageXml(config, deps, 'ament_cmake'),
    });

    // CMakeLists.txt
    files.push({
      path: 'CMakeLists.txt',
      content: this.generateCMakeLists(config, deps),
    });

    // Generate each node
    for (const node of config.nodes) {
      files.push({
        path: `include/${pkgName}/${toSnakeCase(node.name)}.hpp`,
        content: this.generateCppHeader(node, pkgName),
      });
      files.push({
        path: `src/${toSnakeCase(node.name)}.cpp`,
        content: this.generateCppSource(node, pkgName),
      });
    }

    return files;
  }

  private generateCMakeLists(config: PackageGenConfig, deps: string[]): string {
    const pkgName = config.name;
    const lines: string[] = [];

    lines.push('# Copyright 2026 VirtusCo');
    lines.push('# Auto-generated by Virtus ROS 2 Studio');
    lines.push('');
    lines.push('cmake_minimum_required(VERSION 3.8)');
    lines.push(`project(${pkgName})`);
    lines.push('');
    lines.push('if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")');
    lines.push('  add_compile_options(-Wall -Wextra -Wpedantic)');
    lines.push('endif()');
    lines.push('');
    lines.push('# Find dependencies');
    for (const dep of deps) {
      lines.push(`find_package(${dep} REQUIRED)`);
    }
    lines.push('');

    // Include directories
    lines.push(`include_directories(include)`);
    lines.push('');

    // Executables
    for (const node of config.nodes) {
      const snakeName = toSnakeCase(node.name);
      lines.push(`# ${node.name} node`);
      lines.push(`add_executable(${snakeName} src/${snakeName}.cpp)`);
      lines.push(`ament_target_dependencies(${snakeName}`);
      for (const dep of deps) {
        lines.push(`  ${dep}`);
      }
      lines.push(')');
      lines.push('');
    }

    // Install
    lines.push('# Install executables');
    lines.push('install(TARGETS');
    for (const node of config.nodes) {
      lines.push(`  ${toSnakeCase(node.name)}`);
    }
    lines.push('  DESTINATION lib/${PROJECT_NAME}');
    lines.push(')');
    lines.push('');

    lines.push('# Install headers');
    lines.push('install(DIRECTORY include/');
    lines.push('  DESTINATION include');
    lines.push(')');
    lines.push('');

    lines.push('# Install launch files');
    lines.push('install(DIRECTORY launch/');
    lines.push('  DESTINATION share/${PROJECT_NAME}/launch');
    lines.push(')');
    lines.push('');

    lines.push('# Install config files');
    lines.push('install(DIRECTORY config/');
    lines.push('  DESTINATION share/${PROJECT_NAME}/config');
    lines.push(')');
    lines.push('');

    lines.push('ament_package()');
    lines.push('');

    return lines.join('\n');
  }

  private generateCppHeader(node: CanvasNodeConfig, pkgName: string): string {
    const className = toPascalCase(node.name);
    const guardName = `${pkgName.toUpperCase()}__${toSnakeCase(node.name).toUpperCase()}_HPP_`;
    const lines: string[] = [];

    lines.push('// Copyright 2026 VirtusCo');
    lines.push(`// Auto-generated by Virtus ROS 2 Studio — ${className} header`);
    lines.push('');
    lines.push(`#ifndef ${guardName}`);
    lines.push(`#define ${guardName}`);
    lines.push('');

    // Includes
    if (node.lifecycle) {
      lines.push('#include <rclcpp_lifecycle/lifecycle_node.hpp>');
    } else {
      lines.push('#include <rclcpp/rclcpp.hpp>');
    }

    // Message includes
    const includes = new Set<string>();
    for (const pub of node.publishers) {
      includes.add(msgTypeToInclude(pub.msgType, 'cpp'));
    }
    for (const sub of node.subscribers) {
      includes.add(msgTypeToInclude(sub.msgType, 'cpp'));
    }
    for (const srv of node.services) {
      includes.add(msgTypeToSrvInclude(srv.srvType, 'cpp'));
    }
    for (const action of node.actions) {
      includes.add(msgTypeToActionInclude(action.actionType, 'cpp'));
      includes.add('#include <rclcpp_action/rclcpp_action.hpp>');
    }
    for (const inc of includes) {
      if (inc) lines.push(inc);
    }

    lines.push('');
    lines.push(`namespace ${pkgName}`);
    lines.push('{');
    lines.push('');

    const baseClass = node.lifecycle ? 'rclcpp_lifecycle::LifecycleNode' : 'rclcpp::Node';
    lines.push(`class ${className} : public ${baseClass}`);
    lines.push('{');
    lines.push('public:');
    lines.push(`  explicit ${className}(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());`);
    lines.push(`  ~${className}() override = default;`);
    lines.push('');

    // Lifecycle callbacks
    if (node.lifecycle) {
      lines.push('  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn');
      lines.push('  on_configure(const rclcpp_lifecycle::State & state) override;');
      lines.push('');
      lines.push('  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn');
      lines.push('  on_activate(const rclcpp_lifecycle::State & state) override;');
      lines.push('');
      lines.push('  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn');
      lines.push('  on_deactivate(const rclcpp_lifecycle::State & state) override;');
      lines.push('');
      lines.push('  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn');
      lines.push('  on_cleanup(const rclcpp_lifecycle::State & state) override;');
      lines.push('');
      lines.push('  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn');
      lines.push('  on_shutdown(const rclcpp_lifecycle::State & state) override;');
      lines.push('');
    }

    lines.push('private:');

    // Subscriber callbacks
    for (const sub of node.subscribers) {
      const cppType = msgTypeToCppType(sub.msgType);
      const callbackName = sub.callback || `${this.topicToCallbackName(sub.topic)}_callback`;
      lines.push(`  void ${callbackName}(const ${cppType}::SharedPtr msg);`);
    }

    // Service callbacks
    for (const srv of node.services) {
      if (srv.role === 'server') {
        const cppType = msgTypeToCppType(srv.srvType);
        const callbackName = `${this.topicToCallbackName(srv.name)}_callback`;
        lines.push(`  void ${callbackName}(`);
        lines.push(`    const std::shared_ptr<${cppType}::Request> request,`);
        lines.push(`    std::shared_ptr<${cppType}::Response> response);`);
      }
    }

    // Timer callbacks
    for (let i = 0; i < node.timers.length; i++) {
      const callbackName = node.timers[i].callback || `timer_${i}_callback`;
      lines.push(`  void ${callbackName}();`);
    }

    // Publisher timer callbacks
    for (const pub of node.publishers) {
      if (pub.hz > 0) {
        const callbackName = `${this.topicToCallbackName(pub.topic)}_publish`;
        lines.push(`  void ${callbackName}();`);
      }
    }

    lines.push('');

    // Member variables — publishers
    for (const pub of node.publishers) {
      const cppType = msgTypeToCppType(pub.msgType);
      const varName = this.topicToVarName(pub.topic, 'pub');
      lines.push(`  rclcpp::Publisher<${cppType}>::SharedPtr ${varName}_;`);
    }

    // Member variables — subscribers
    for (const sub of node.subscribers) {
      const cppType = msgTypeToCppType(sub.msgType);
      const varName = this.topicToVarName(sub.topic, 'sub');
      lines.push(`  rclcpp::Subscription<${cppType}>::SharedPtr ${varName}_;`);
    }

    // Member variables — services
    for (const srv of node.services) {
      const cppType = msgTypeToCppType(srv.srvType);
      const varName = this.topicToVarName(srv.name, srv.role === 'server' ? 'srv' : 'cli');
      if (srv.role === 'server') {
        lines.push(`  rclcpp::Service<${cppType}>::SharedPtr ${varName}_;`);
      } else {
        lines.push(`  rclcpp::Client<${cppType}>::SharedPtr ${varName}_;`);
      }
    }

    // Member variables — timers
    for (let i = 0; i < node.timers.length; i++) {
      lines.push(`  rclcpp::TimerBase::SharedPtr timer_${i}_;`);
    }

    // Member variables — publisher timers
    for (const pub of node.publishers) {
      if (pub.hz > 0) {
        const varName = `${this.topicToCallbackName(pub.topic)}_timer`;
        lines.push(`  rclcpp::TimerBase::SharedPtr ${varName}_;`);
      }
    }

    lines.push('};');
    lines.push('');
    lines.push(`}  // namespace ${pkgName}`);
    lines.push('');
    lines.push(`#endif  // ${guardName}`);
    lines.push('');

    return lines.join('\n');
  }

  private generateCppSource(node: CanvasNodeConfig, pkgName: string): string {
    const className = toPascalCase(node.name);
    const lines: string[] = [];

    lines.push('// Copyright 2026 VirtusCo');
    lines.push(`// Auto-generated by Virtus ROS 2 Studio — ${className} implementation`);
    lines.push('');
    lines.push(`#include "${pkgName}/${toSnakeCase(node.name)}.hpp"`);
    lines.push('');
    lines.push('#include <chrono>');
    lines.push('#include <functional>');
    lines.push('#include <memory>');
    lines.push('');
    lines.push('using namespace std::chrono_literals;');
    lines.push('');
    lines.push(`namespace ${pkgName}`);
    lines.push('{');
    lines.push('');

    // Constructor
    lines.push(`${className}::${className}(const rclcpp::NodeOptions & options)`);
    const baseClass = node.lifecycle ? 'LifecycleNode' : 'Node';
    lines.push(`: ${baseClass}("${toSnakeCase(node.name)}", options)`);
    lines.push('{');
    lines.push(`  RCLCPP_INFO(this->get_logger(), "${className} initializing...");`);
    lines.push('');

    // Parameters
    if (node.parameters.length > 0) {
      lines.push('  // Parameters');
      for (const param of node.parameters) {
        const defaultVal = this.cppDefaultValue(param.type, param.default);
        const cppType = this.paramTypeToCpp(param.type);
        lines.push(`  this->declare_parameter<${cppType}>("${param.name}", ${defaultVal});`);
      }
      lines.push('');
    }

    // Publishers
    if (node.publishers.length > 0) {
      lines.push('  // Publishers');
      for (const pub of node.publishers) {
        const cppType = msgTypeToCppType(pub.msgType);
        const varName = this.topicToVarName(pub.topic, 'pub');
        const qos = this.inferCppQoS(pub.topic, pub.msgType);
        lines.push(`  ${varName}_ = this->create_publisher<${cppType}>("${pub.topic}", ${qos});`);
      }
      lines.push('');
    }

    // Subscribers
    if (node.subscribers.length > 0) {
      lines.push('  // Subscribers');
      for (const sub of node.subscribers) {
        const cppType = msgTypeToCppType(sub.msgType);
        const varName = this.topicToVarName(sub.topic, 'sub');
        const callbackName = sub.callback || `${this.topicToCallbackName(sub.topic)}_callback`;
        const qos = this.inferCppQoS(sub.topic, sub.msgType);
        lines.push(`  ${varName}_ = this->create_subscription<${cppType}>(`);
        lines.push(`    "${sub.topic}", ${qos},`);
        lines.push(`    std::bind(&${className}::${callbackName}, this, std::placeholders::_1));`);
      }
      lines.push('');
    }

    // Services
    if (node.services.length > 0) {
      lines.push('  // Services');
      for (const srv of node.services) {
        const cppType = msgTypeToCppType(srv.srvType);
        const varName = this.topicToVarName(srv.name, srv.role === 'server' ? 'srv' : 'cli');
        if (srv.role === 'server') {
          const callbackName = `${this.topicToCallbackName(srv.name)}_callback`;
          lines.push(`  ${varName}_ = this->create_service<${cppType}>(`);
          lines.push(`    "${srv.name}",`);
          lines.push(`    std::bind(&${className}::${callbackName}, this, std::placeholders::_1, std::placeholders::_2));`);
        } else {
          lines.push(`  ${varName}_ = this->create_client<${cppType}>("${srv.name}");`);
        }
      }
      lines.push('');
    }

    // Timers
    if (node.timers.length > 0) {
      lines.push('  // Timers');
      for (let i = 0; i < node.timers.length; i++) {
        const timer = node.timers[i];
        const callbackName = timer.callback || `timer_${i}_callback`;
        lines.push(`  timer_${i}_ = this->create_wall_timer(`);
        lines.push(`    std::chrono::milliseconds(${timer.periodMs}),`);
        lines.push(`    std::bind(&${className}::${callbackName}, this));`);
      }
      lines.push('');
    }

    // Publisher timers
    for (const pub of node.publishers) {
      if (pub.hz > 0) {
        const callbackName = `${this.topicToCallbackName(pub.topic)}_publish`;
        const periodMs = Math.round(1000 / pub.hz);
        const varName = `${this.topicToCallbackName(pub.topic)}_timer`;
        lines.push(`  ${varName}_ = this->create_wall_timer(`);
        lines.push(`    std::chrono::milliseconds(${periodMs}),`);
        lines.push(`    std::bind(&${className}::${callbackName}, this));`);
      }
    }

    lines.push(`  RCLCPP_INFO(this->get_logger(), "${className} initialized");`);
    lines.push('}');
    lines.push('');

    // Subscriber callbacks
    for (const sub of node.subscribers) {
      const cppType = msgTypeToCppType(sub.msgType);
      const callbackName = sub.callback || `${this.topicToCallbackName(sub.topic)}_callback`;
      lines.push(`void ${className}::${callbackName}(const ${cppType}::SharedPtr msg)`);
      lines.push('{');
      lines.push(`  RCLCPP_DEBUG(this->get_logger(), "Received on ${sub.topic}");`);
      lines.push('  (void)msg;');
      lines.push('}');
      lines.push('');
    }

    // Service callbacks
    for (const srv of node.services) {
      if (srv.role === 'server') {
        const cppType = msgTypeToCppType(srv.srvType);
        const callbackName = `${this.topicToCallbackName(srv.name)}_callback`;
        lines.push(`void ${className}::${callbackName}(`);
        lines.push(`  const std::shared_ptr<${cppType}::Request> request,`);
        lines.push(`  std::shared_ptr<${cppType}::Response> response)`);
        lines.push('{');
        lines.push(`  RCLCPP_INFO(this->get_logger(), "Service ${srv.name} called");`);
        lines.push('  (void)request;');
        lines.push('  (void)response;');
        lines.push('}');
        lines.push('');
      }
    }

    // Timer callbacks
    for (let i = 0; i < node.timers.length; i++) {
      const callbackName = node.timers[i].callback || `timer_${i}_callback`;
      lines.push(`void ${className}::${callbackName}()`);
      lines.push('{');
      lines.push(`  RCLCPP_DEBUG(this->get_logger(), "Timer ${i} fired");`);
      lines.push('}');
      lines.push('');
    }

    // Publisher timer callbacks
    for (const pub of node.publishers) {
      if (pub.hz > 0) {
        const cppType = msgTypeToCppType(pub.msgType);
        const varName = this.topicToVarName(pub.topic, 'pub');
        const callbackName = `${this.topicToCallbackName(pub.topic)}_publish`;
        lines.push(`void ${className}::${callbackName}()`);
        lines.push('{');
        lines.push(`  auto msg = ${cppType}();`);
        lines.push(`  ${varName}_->publish(msg);`);
        lines.push(`  RCLCPP_DEBUG(this->get_logger(), "Published on ${pub.topic}");`);
        lines.push('}');
        lines.push('');
      }
    }

    // Lifecycle callbacks
    if (node.lifecycle) {
      const lcReturn = 'rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn';
      for (const [method, desc] of [
        ['on_configure', 'Configuring'],
        ['on_activate', 'Activating'],
        ['on_deactivate', 'Deactivating'],
        ['on_cleanup', 'Cleaning up'],
        ['on_shutdown', 'Shutting down'],
      ] as const) {
        lines.push(`${lcReturn}`);
        lines.push(`${className}::${method}(const rclcpp_lifecycle::State & state)`);
        lines.push('{');
        lines.push(`  RCLCPP_INFO(this->get_logger(), "${desc}...");`);
        lines.push('  (void)state;');
        lines.push(`  return ${lcReturn}::SUCCESS;`);
        lines.push('}');
        lines.push('');
      }
    }

    lines.push(`}  // namespace ${pkgName}`);
    lines.push('');

    // main()
    lines.push(`int main(int argc, char ** argv)`);
    lines.push('{');
    lines.push('  rclcpp::init(argc, argv);');
    lines.push(`  auto node = std::make_shared<${pkgName}::${className}>();`);
    lines.push('  rclcpp::spin(node);');
    lines.push('  rclcpp::shutdown();');
    lines.push('  return 0;');
    lines.push('}');
    lines.push('');

    return lines.join('\n');
  }

  // ── Shared Generators ─────────────────────────────────────────────

  private generatePackageXml(
    config: PackageGenConfig,
    deps: string[],
    buildType: 'ament_cmake' | 'ament_python'
  ): string {
    const lines: string[] = [];
    lines.push('<?xml version="1.0"?>');
    lines.push('<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>');
    lines.push('<package format="3">');
    lines.push(`  <name>${config.name}</name>`);
    lines.push('  <version>0.1.0</version>');
    lines.push(`  <description>${config.description}</description>`);
    lines.push('  <maintainer email="dev@virtusco.io">VirtusCo</maintainer>');
    lines.push('  <license>Proprietary</license>');
    lines.push('');
    lines.push(`  <buildtool_depend>${buildType}</buildtool_depend>`);
    lines.push('');

    for (const dep of deps) {
      lines.push(`  <depend>${dep}</depend>`);
    }

    lines.push('');

    if (buildType === 'ament_python') {
      lines.push('  <test_depend>ament_copyright</test_depend>');
      lines.push('  <test_depend>ament_flake8</test_depend>');
      lines.push('  <test_depend>ament_pep257</test_depend>');
      lines.push('  <test_depend>python3-pytest</test_depend>');
    } else {
      lines.push('  <test_depend>ament_lint_auto</test_depend>');
      lines.push('  <test_depend>ament_lint_common</test_depend>');
    }

    lines.push('');
    lines.push(`  <export>`);
    lines.push(`    <build_type>${buildType}</build_type>`);
    lines.push(`  </export>`);
    lines.push('</package>');
    lines.push('');

    return lines.join('\n');
  }

  private generateLaunchFile(config: PackageGenConfig): GeneratedFile {
    const lines: string[] = [];
    lines.push('# Copyright 2026 VirtusCo');
    lines.push('# Auto-generated by Virtus ROS 2 Studio');
    lines.push('');
    lines.push('import os');
    lines.push('');
    lines.push('from ament_index_python.packages import get_package_share_directory');
    lines.push('from launch import LaunchDescription');
    lines.push('from launch.actions import DeclareLaunchArgument');
    lines.push('from launch.substitutions import LaunchConfiguration');
    lines.push('from launch_ros.actions import Node');
    lines.push('');
    lines.push('');
    lines.push('def generate_launch_description():');
    lines.push(`    pkg_share = get_package_share_directory('${config.name}')`);
    lines.push(`    params_file = os.path.join(pkg_share, 'config', '${config.name}_params.yaml')`);
    lines.push('');
    lines.push('    return LaunchDescription([');

    // Launch arguments
    lines.push("        DeclareLaunchArgument('use_sim_time', default_value='false',");
    lines.push("            description='Use simulation time'),");
    lines.push('');

    // Nodes
    for (let i = 0; i < config.nodes.length; i++) {
      const node = config.nodes[i];
      const isLast = i === config.nodes.length - 1;
      const snakeName = toSnakeCase(node.name);

      lines.push('        Node(');
      lines.push(`            package='${config.name}',`);
      lines.push(`            executable='${snakeName}',`);
      lines.push(`            name='${snakeName}',`);
      lines.push('            output=\'screen\',');
      lines.push(`            parameters=[params_file, {{'use_sim_time': LaunchConfiguration('use_sim_time')}}],`);
      lines.push(`        )${isLast ? '' : ','}`)
    }

    lines.push('    ])');
    lines.push('');

    return {
      path: `launch/${config.name}_launch.py`,
      content: lines.join('\n'),
    };
  }

  private generateParamsYaml(config: PackageGenConfig): GeneratedFile {
    const lines: string[] = [];
    lines.push('# Copyright 2026 VirtusCo');
    lines.push('# Auto-generated by Virtus ROS 2 Studio');
    lines.push('');

    for (const node of config.nodes) {
      const snakeName = toSnakeCase(node.name);
      lines.push(`${snakeName}:`);
      lines.push('  ros__parameters:');

      if (node.parameters.length === 0) {
        lines.push('    use_sim_time: false');
      } else {
        for (const param of node.parameters) {
          const yamlVal = this.yamlValue(param.type, param.default);
          lines.push(`    ${param.name}: ${yamlVal}`);
        }
      }

      lines.push('');
    }

    return {
      path: `config/${config.name}_params.yaml`,
      content: lines.join('\n'),
    };
  }

  // ── Helpers ───────────────────────────────────────────────────────

  private addPythonImport(
    imports: Map<string, Set<string>>,
    fullType: string,
    category: 'msg' | 'srv' | 'action' = 'msg'
  ): void {
    const parts = fullType.split('/');
    if (parts.length !== 2) return;
    const importPath = `${parts[0]}.${category}`;
    if (!imports.has(importPath)) {
      imports.set(importPath, new Set());
    }
    imports.get(importPath)!.add(parts[1]);
  }

  private needsSensorQoS(node: CanvasNodeConfig): boolean {
    const sensorTopics = ['/scan', '/image', '/imu', '/camera', '/pointcloud', '/range'];
    for (const pub of node.publishers) {
      if (sensorTopics.some((t) => pub.topic.includes(t))) return true;
    }
    for (const sub of node.subscribers) {
      if (sensorTopics.some((t) => sub.topic.includes(t))) return true;
    }
    return false;
  }

  private inferPythonQoS(topic: string, msgType: string): string {
    if (this.isSensorTopic(topic, msgType)) return 'SENSOR_QOS';
    return '10';
  }

  private inferCppQoS(topic: string, msgType: string): string {
    if (this.isSensorTopic(topic, msgType)) {
      return 'rclcpp::SensorDataQoS().reliable()';
    }
    if (topic === '/tf_static') {
      return 'rclcpp::QoS(10).transient_local()';
    }
    return '10';
  }

  private isSensorTopic(topic: string, msgType: string): boolean {
    const sensorTopics = ['/scan', '/image_raw', '/camera', '/imu', '/pointcloud', '/range'];
    const sensorMsgs = ['sensor_msgs/LaserScan', 'sensor_msgs/Image', 'sensor_msgs/Imu',
      'sensor_msgs/PointCloud2', 'sensor_msgs/Range', 'sensor_msgs/CameraInfo'];
    return sensorTopics.some((t) => topic.includes(t)) || sensorMsgs.includes(msgType);
  }

  private topicToVarName(topic: string, prefix: string): string {
    return prefix + '_' + topic.replace(/^\//, '').replace(/\//g, '_').replace(/[^a-zA-Z0-9_]/g, '');
  }

  private topicToCallbackName(topic: string): string {
    return topic.replace(/^\//, '').replace(/\//g, '_').replace(/[^a-zA-Z0-9_]/g, '');
  }

  private pythonDefaultValue(type: string, value: string): string {
    if (type === 'bool') return value === 'true' || value === 'True' ? 'True' : 'False';
    if (type === 'int') return value || '0';
    if (type === 'float') return value || '0.0';
    return `'${value || ''}'`;
  }

  private cppDefaultValue(type: string, value: string): string {
    if (type === 'bool') return value === 'true' ? 'true' : 'false';
    if (type === 'int') return value || '0';
    if (type === 'float') return value || '0.0';
    return `"${value || ''}"`;
  }

  private paramTypeToCpp(type: string): string {
    if (type === 'bool') return 'bool';
    if (type === 'int') return 'int64_t';
    if (type === 'float') return 'double';
    return 'std::string';
  }

  private yamlValue(type: string, value: string): string {
    if (type === 'bool') return value === 'true' || value === 'True' ? 'true' : 'false';
    if (type === 'int') return value || '0';
    if (type === 'float') return value || '0.0';
    return `"${value || ''}"`;
  }
}

// ── Module-Level Helpers ──────────────────────────────────────────────

/**
 * Extracts the package name from a full message type.
 * "sensor_msgs/LaserScan" -> "sensor_msgs"
 */
export function msgTypeToPackage(msgType: string): string {
  return msgType.split('/')[0] ?? '';
}

/**
 * Generates the C++ include for a message type.
 * "sensor_msgs/LaserScan" -> '#include <sensor_msgs/msg/laser_scan.hpp>'
 */
export function msgTypeToInclude(msgType: string, language: 'cpp' | 'python'): string {
  const parts = msgType.split('/');
  if (parts.length !== 2) return '';
  const pkg = parts[0];
  const name = parts[1];

  if (language === 'cpp') {
    const snakeName = camelToSnake(name);
    return `#include <${pkg}/msg/${snakeName}.hpp>`;
  }
  return `from ${pkg}.msg import ${name}`;
}

/**
 * Generates the C++ include for a service type.
 */
export function msgTypeToSrvInclude(srvType: string, language: 'cpp' | 'python'): string {
  const parts = srvType.split('/');
  if (parts.length !== 2) return '';
  const pkg = parts[0];
  const name = parts[1];

  if (language === 'cpp') {
    const snakeName = camelToSnake(name);
    return `#include <${pkg}/srv/${snakeName}.hpp>`;
  }
  return `from ${pkg}.srv import ${name}`;
}

/**
 * Generates the C++ include for an action type.
 */
export function msgTypeToActionInclude(actionType: string, language: 'cpp' | 'python'): string {
  const parts = actionType.split('/');
  if (parts.length !== 2) return '';
  const pkg = parts[0];
  const name = parts[1];

  if (language === 'cpp') {
    const snakeName = camelToSnake(name);
    return `#include <${pkg}/action/${snakeName}.hpp>`;
  }
  return `from ${pkg}.action import ${name}`;
}

/**
 * Converts a message type to its C++ namespaced form.
 * "sensor_msgs/LaserScan" -> "sensor_msgs::msg::LaserScan"
 */
export function msgTypeToCppType(msgType: string): string {
  const parts = msgType.split('/');
  if (parts.length !== 2) return msgType;
  return `${parts[0]}::msg::${parts[1]}`;
}

/**
 * Extracts just the class name from a full message type.
 * "sensor_msgs/LaserScan" -> "LaserScan"
 */
export function msgTypeToClassName(msgType: string): string {
  const parts = msgType.split('/');
  return parts[parts.length - 1];
}

/**
 * Infers QoS profile based on topic name and message type.
 */
export function inferQoS(topic: string, msgType: string): string {
  const sensorTopics = ['/scan', '/image_raw', '/camera', '/imu', '/pointcloud', '/range'];
  const sensorMsgs = ['sensor_msgs/LaserScan', 'sensor_msgs/Image', 'sensor_msgs/Imu',
    'sensor_msgs/PointCloud2', 'sensor_msgs/Range'];

  if (sensorTopics.some((t) => topic.includes(t)) || sensorMsgs.includes(msgType)) {
    return 'SensorDataQoS';
  }
  if (topic === '/tf_static') {
    return 'StaticBroadcasterQoS';
  }
  return 'default';
}

// ── String Utilities ────────────────────────────────────────────────

function toSnakeCase(name: string): string {
  return name
    .replace(/([A-Z])/g, '_$1')
    .replace(/[\s-]+/g, '_')
    .replace(/^_/, '')
    .replace(/__+/g, '_')
    .toLowerCase();
}

function toPascalCase(name: string): string {
  return name
    .replace(/[_\s-]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
}

function camelToSnake(name: string): string {
  return name
    .replace(/([A-Z])/g, '_$1')
    .replace(/^_/, '')
    .toLowerCase();
}
